#!/usr/bin/env bash
# Installing nginx
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
nginx -v
# Setup ports 80 and 22 enable
sudo ufw allow 'OpenSSH'
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
# Setup the html file 
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
