#!/usr/bin/env bash
# Installing nginx
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# Setup 301 Moved Permanently
redirection="\\\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/ a $redirection" /etc/nginx/sites-available/default
# Start nginx
sudo service nginx start
