#!/usr/bin/env bash
#  This script generates a MySQL dump and creates a compressed archive out of it
mysqldump -u root -p"$1" --all-databases > backup.sql
date=$(date +"%d-%m-%Y")
tar -czf "$date".tar.gz backup.sql
