#!/usr/bin/env bash
# This script setup nginx to listen port 80
sudo apt-get install -y psmisc
sudo pkill nginx
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
