#!/usr/bin/env bash
# This script setup nginx to listen port 80 while it's not running
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 "$(cat /run/nginx.pid)"
