#!/usr/bin/env bash
# displays numbers from 1 to 100

for ((itr = 1; itr <= 100; itr++))
do
    if (( itr % 3 == 0 && itr % 5 == 0))
    then
	echo "FizzBuzz"
    elif (( itr % 3 == 0 ))
    then
	echo "Fizz"
    elif (( itr % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo "$itr"
    fi
done
