#!/usr/bin/env bash
# displays bad luck, good luck and Holberton School

i=0
while ((i <= 9))
do
	if ((i == 3))
	then
	    echo "bad luck"
	elif ((i == 7))
	then
	    echo "good luck"
	else
	    echo "Holberton School"
	fi
	((i++))
done
