#!/usr/bin/env bash
# Installing nginx
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo apt-get update
# This script setup nginx to listen port 8080
sudo sed -i "21,22 s/80/8080/" /etc/nginx/sites-enabled/default
# This script setup the nginx user
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
# This script change the owner from root to nginx
sudo chown nginx:nginx /var/log/nginx/.
sudo chown nginx:nginx /var/log/nginx/..
sudo chown nginx:nginx /var/log/nginx/access.log
sudo chown nginx:nginx /var/log/nginx/error.log
sudo touch /run/nginx.pid
sudo chown nginx:nginx /run/nginx.pid
sudo chmod u+wr /etc/nginx/nginx.conf
# Start nginx
sudo pkill -9 apache2
sudo pkill nginx
sudo service nginx start
sudo service nginx stop
su nginx -c "service nginx start"
